# Generated by Django 4.1.4 on 2022-12-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('is_killer', models.BooleanField()),
                ('is_survivor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_exhaust', models.BooleanField()),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbd_trivia.character')),
            ],
        ),
    ]
